version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - hamzaremmal
    reviewers:
      - hamzaremmal
  - package-ecosystem: bundler
    directory: '/docs/_spec'
    schedule:
      interval: weekly
    assignees:
      - hamzaremmal
    reviewers:
      - hamzaremmal
      
