includes:
    - projects.yml
    - implicits.yml
    - typing.yml
    - exhaustivity.yml
    - misc.yml
    - empty.yml
    - quotes.yml
    - tuples.yml
    - compiletime.yml


config:
    pr_base_url: "https://github.com/scala/scala3/pull/"
